CREATE TABLE employee_busted (
BUST_I NUMBER NOT NULL,
REQUEST_I NUMBER NOT NULL,
  CONSTRAINT pk_bustid PRIMARY KEY(BUST_I)
);
CREATE TABLE employee_busted_info (
    BUST_I NUMBER NOT NULL,
  EMPLOYEE_I NUMBER NOT NULL,
  EMPLOYEE_NAME VARCHAR2(400),
  CONSTRAINT pk_crewinfoid PRIMARY KEY(BUST_I, EMPLOYEE_I),
  CONSTRAINT fk_swapbust FOREIGN KEY(BUST_I) REFERENCES swap_crew_bust(BUST_I)
);

CREATE SEQUENCE employee_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;